#!/bin/bash
# Script de déploiement avec correction du logo
# Pour corriger le problème du logo manquant sur Render.com

echo "🚀 DÉPLOIEMENT DOUKA KM avec correction du logo"
echo "==============================================="

echo "📝 Étapes à suivre pour corriger le logo sur Render.com:"
echo ""
echo "1. 📤 Déployer les modifications:"
echo "   git add ."
echo "   git commit -m \"Fix: Ajouter paramètres par défaut pour logo_url et logo_alt_text\""
echo "   git push origin main"
echo ""
echo "2. ⏳ Attendre la fin du déploiement sur Render.com"
echo ""
echo "3. 🔧 Corriger les paramètres en base via l'une de ces méthodes:"
echo ""
echo "   Méthode A - Via l'interface web:"
echo "   - Aller sur: https://douka-km.onrender.com/admin/fix-logo-urgent"
echo "   - Cette route ajoutera automatiquement les paramètres manquants"
echo ""
echo "   Méthode B - Via debug (pour diagnostic):"
echo "   - Aller sur: https://douka-km.onrender.com/debug/site-settings"
echo "   - Vérifier l'état des paramètres"
echo ""
echo "   Méthode C - Via le shell Render (avancé):"
echo "   - python render_fix_logo_urgent.py"
echo ""
echo "4. ✅ Vérifier que le logo s'affiche correctement sur le site"
echo ""
echo "📋 Fichiers modifiés dans cette correction:"
echo "   - app_final_with_db.py: Ajout des paramètres par défaut dans get_all_site_settings()"
echo "   - render_fix_logo_urgent.py: Script de correction pour production"
echo "   - Routes d'urgence: /admin/fix-logo-urgent et /debug/site-settings"
echo ""
echo "🔍 Le problème était que:"
echo "   - site_settings.logo_url était undefined/null en production"
echo "   - Les paramètres par défaut n'étaient pas définis"
echo "   - Le fallback dans le template ne fonctionnait pas correctement"
echo ""
echo "✨ Avec cette correction:"
echo "   - get_all_site_settings() retourne toujours /static/img/logo.png par défaut"
echo "   - Routes d'urgence permettent la correction immédiate en production"
echo "   - Fichiers statiques sont explicitement servis si nécessaire"
